FROM php:8-fpm

RUN apt-get update && apt-get install -y git unzip

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
  install-php-extensions gd xdebug pdo_mysql bz2

RUN install-php-extensions @composer

COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

EXPOSE 9000
CMD ["php-fpm"]