FROM php:7.4-fpm

RUN apt-get update && apt-get install -y git unzip

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
  install-php-extensions gd xdebug pdo_mysql bz2

RUN install-php-extensions @composer

RUN echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.remote_port=9001' >>  /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.remote_cookie_expire_time=36000' >>  /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.mode = debug' >>  /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.start_with_request = yes' >>  /usr/local/etc/php/conf.d/xdebug.ini \
  && echo 'xdebug.remote_connect_back = 1' >>  /usr/local/etc/php/conf.d/xdebug.ini

EXPOSE 9000
CMD ["php-fpm"]