version: "3.1"
services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    volumes:
      - .db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306"

  php:
    container_name: php
    working_dir: /var/www
    volumes:
      - .:/var/www
    # ports:
    #   - "9000:9000"
    build:
      context: docker/php
      dockerfile: dockerfile
    environment:
      APP_ENV: "local"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/server.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/conf:/etc/nginx/custom:ro
    ports:
      - "80:80"
    depends_on:
      - php

networks:
  app-network:
    driver: bridge
