name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run composer
        uses: php-actions/composer@v5

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Run node scripts
        run: npm install && npm i -D postcss postcss-cli && npm run build:css
        env:
          NODE_ENV: 'production' 
      
      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"
      - name: Deploying on remote server
        script: |
          echo "Copying files from staging"
          sudo rsync --filter=':- .gitignore' -avz ~/staging/ /var/www/atlantaned.space/banbus/
