name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run composer
        uses: php-actions/composer@v5

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          check-latest: true

      - name: Build node assets
        run: npm install && NODE_ENV=production npm run build:prod

      - name: Delete un-needed node files
        run: rm -rf ./node_modules/

      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"
          rm: true

      - name: Deploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Copying files from staging..."
            rsync -aqz --delete ~/staging/ ~/serv/www/${{ secrets.PROD_DOMAIN }}
