name: CI
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run composer
        uses: php-actions/composer@v5

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true

      - name: Run node scripts
        run: npm install && npm i -D postcss postcss-cli && npm run build:css
        env:
          NODE_ENV: 'production'
      
      - name: Delete un-needed node files
        run: rm -rf ./node_modules/
      
      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"

      - name: Deploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Copying files from staging"
            sudo mkdir /var/www/atlantaned.space/public/banbus/
            sudo rm -rf /var/www/atlantaned.space/public/banbus/*
            sudo rm -rf /var/www/atlantaned.space/banbus/tmp/*
            sudo rsync -aqz ~/staging/ /var/www/atlantaned.space/banbus/
            sudo mv /var/www/atlantaned.space/banbus/public/* /var/www/atlantaned.space/public/banbus/
            sudo sed -i 's/\/app/\/..\/banbus\/app/g' /var/www/atlantaned.space/public/banbus/index.php
            sudo chown -R www-data:www-data /var/www/atlantaned.space
