name: CI
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Run composer & install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: latest
          args: --ignore-platform-reqs

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          check-latest: true

      - name: Build node assets
        run: npm install && NODE_ENV=production npm run build:prod

      - name: Delete un-needed node files
        run: rm -rf ./node_modules/

      - name: Pushing artifact to deployment server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "./"
          target: "~/staging"
          rm: true

      - name: Deploying on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "Stashing configuration files..."
            tar -cjf conf.tar -C serv/www/${{ secrets.PROD_DOMAIN }}/app/conf/ .
            echo "Copying files from staging..."
            rsync -aqz --delete --filter=':- .gitignore' ~/staging/ ~/serv/www/${{ secrets.PROD_DOMAIN }}
            echo "Wiping previous template stash"
            rm -rf ~/serv/www/${{ secrets.PROD_DOMAIN }}/tmp/twig/*
            echo "Restoring configuration..."
            tar xvf conf.tar -C serv/www/${{ secrets.PROD_DOMAIN }}/app/conf
            mv ~/serv/www/conf ~/${{ secrets.PROD_DOMAIN }}/app/
            echo "Done!"
      - name: send message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: Statbus has been updated! See what's new at ${{ secrets.PROD_DOMAIN }}/changelog 
